### ISSUE TITLE
RTF to PDF conversion failing

### ISSUE THREAD

**Issue by NitishKumar-Wellsky** [iron-software/IronPDF-for-Java#44]
Error from ironpdfengine.log

[2024-10-18 19:42:30] IronSoftware.Exceptions.IronPdfInputException: Error while reading RTF file. IronPDF does not support elements in this file.
   at IronPdf.Extensions.RtfHelper.RtfStringToHtmlConvertor(String rtfString) in D:\a\1\src\IronPdf\Extensions\RtfHelper.cs:line 27
   at IronPdfEngine.IronPdfServiceHandler.Chrome_Render_RtfToPdf(IAsyncStreamReader`1 requestStream, ServerCallContext context) in D:\a\1\src\IronPdfEngine\IronPdfServiceHandler.Render.cs:line 149
   
Application error log

com.ironsoftware.ironpdf.exception.IronPdfInputException: Error while reading RTF file. IronPDF does not support elements in this file.
	at    at IronPdf.Extensions.RtfHelper.RtfStringToHtmlConvertor(String rtfString) in D:\a\1\src\IronPdf\Extensions\RtfHelper.cs:line 27
   at IronPdfEngine.IronPdfServiceHandler.Chrome_Render_RtfToPdf(IAsyncStreamReader`1 requestStream, ServerCallContext context) in D:\a\1\src\IronPdfEngine\IronPdfServiceHandler.Render.cs:line 149.ironpdf(ironpdf:0) ~[na:na]
	at    at IronPdf.Extensions.RtfHelper.RtfStringToHtmlConvertor(String rtfString) in D:\a\1\src\IronPdf\Extensions\RtfHelper.cs:line 27
   at IronPdfEngine.IronPdfServiceHandler.Chrome_Render_RtfToPdf(IAsyncStreamReader`1 requestStream, ServerCallContext context) in D:\a\1\src\IronPdfEngine\IronPdfServiceHandler.Render.cs:line 149.ironpdf(ironpdf:0) ~[na:na]
[file-sample_1MB.rtf.zip](https://github.com/user-attachments/files/17436932/file-sample_1MB.rtf.zip)

I have attached the sample rtf file in zip

**Comment by chaknith-ironsoftware** [comment]
@NitishKumar-Wellsky hi, could you send an email to support@ironsoftware.com. We do issue tracking through email and not on Github.
